name: photo
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dino_generator: ^1.0.0-pre.4
  retrofit_generator: ^6.0.0+3

flutter:
  uses-material-design: true
