name: core

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pansy_arch_flutter:
    git:
      url: https://github.com/mocki-toki/pansy_architecture.git
      path: packages/pansy_arch_flutter
  pansy_arch_go_router:
    git:
      url: https://github.com/mocki-toki/pansy_architecture.git
      path: packages/pansy_arch_go_router

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  fpdart: ^0.5.0
  equatable: ^2.0.5
  dio: ^5.1.1
  retrofit: ^4.0.1
  dino: ^1.0.0-pre.1
  flutter_bloc: ^8.1.2
  cached_network_image: ^3.2.3
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
